// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu4vcqmWlLFvrCWnh9D_VvTSeuCdelxeA',
    appId: '1:420624463594:web:ab28a00054dcee10710993',
    messagingSenderId: '420624463594',
    projectId: 'connevo',
    authDomain: 'connevo.firebaseapp.com',
    storageBucket: 'connevo.firebasestorage.app',
    measurementId: 'G-YG6PTPNB4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu4vcqmWlLFvrCWnh9D_VvTSeuCdelxeA',
    appId: '1:420624463594:android:cc46e58f3b48348d710993',
    messagingSenderId: '420624463594',
    projectId: 'connevo',
    storageBucket: 'connevo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu4vcqmWlLFvrCWnh9D_VvTSeuCdelxeA',
    appId: '1:420624463594:ios:68a130566569710b710993',
    messagingSenderId: '420624463594',
    projectId: 'connevo',
    storageBucket: 'connevo.firebasestorage.app',
    androidClientId: '420624463594-e4e0fj62mvvvl0mu8u71bg055rkcoia8.apps.googleusercontent.com',
    iosClientId: '420624463594-d83chksjk26u68c4119ee2ciqsai5qdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu4vcqmWlLFvrCWnh9D_VvTSeuCdelxeA',
    appId: '1:420624463594:ios:68a130566569710b710993',
    messagingSenderId: '420624463594',
    projectId: 'connevo',
    storageBucket: 'connevo.firebasestorage.app',
    androidClientId: '420624463594-e4e0fj62mvvvl0mu8u71bg055rkcoia8.apps.googleusercontent.com',
    iosClientId: '420624463594-d83chksjk26u68c4119ee2ciqsai5qdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu4vcqmWlLFvrCWnh9D_VvTSeuCdelxeA',
    appId: '1:420624463594:web:8743cfeb3a4a0a6f710993',
    messagingSenderId: '420624463594',
    projectId: 'connevo',
    authDomain: 'connevo.firebaseapp.com',
    storageBucket: 'connevo.firebasestorage.app',
    measurementId: 'G-W0XC6GXB7B',
  );

}